# full_name = "Lika Matsaberidze"
# # print(len(full_name))
# # print(full_name[0])
# # print(full_name[12])
# # print("d" in full_name)
# # print("k" in full_name)
# # print("l" not in full_name)
# # print(full_name[2:7])
# # print(full_name[2:9:2])
# # print(full_name[:7])
# # print(full_name[7:])
# # print(full_name[-1])
# # print(full_name[-10])
# # print(full_name[-10]+ "kheil")
# # print(full_name[-2:-10:-3])
# # print(full_name.upper())
# # print(full_name.replace(" ", "#"))
# # print(full_name.replace("i", "%"))


# full_name = "nikolozi nikolaevi"
# # print(len(full_name))
# # print(full_name[5])
# # print(full_name[8])
# # print("k" in full_name)
# # print("z" in full_name)
# # print("d" not in full_name)
# # print(full_name[4:9])
# # print(full_name[2:10:3])
# # print(full_name[ :8])
# # print(full_name[5:])
# # print(full_name[-3])
# # print(full_name[-2:-6])
# # print(full_name[-2:-8:-2])
# # print(full_name[-5] + "kin")
# # print(full_name.upper())
# # full_name2= "NIKOLOZI NIKOLAEVI"
# # print(full_name2.lower())
# # print(full_name.replace("n", "^"))